
name: "web_app"
mode: "dev"
port: 8081
start_time: "2020-07-28"

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "182.92.0.107"
  port: 3306
  user: "root"
  password: "991124"
  dbname: "bulebell_schema"
  max_open_conns: 30
  max_idle_conns: 5
redis:
  host: "127.0.0.1"
  port: 13306
  db: 0
